extends:
  - ../preset/classification_train.yaml
  - ../model/classification/resnet101.yaml

data:
  metadata: data/aligned_v2/metadata.json
  split_file: data/splits/2026-03-08.yaml
  modalities: [t2, adc, calc]
  zero_pad_missing: true
  seg_pred_dir: data/seg_preds
  selection:
    method: center_crop_pad
    source: hybrid
    jitter: 2
    min_prob: 0.3
  depth:
    strategy: center_crop_pad
    depth: 16
  roi:
    crop_size: 192
    output_size: 256
    use_roi: true
