extends:
  - ../preset/segmentation_train.yaml
  - ../model/segmentation/segresnet.yaml

data:
  metadata: data/aligned_v2/metadata.json
  split_file: data/splits/2026-03-08.yaml
  modalities: [t2, adc, calc]
  zero_pad_missing: true
  stack_depth: 5
